### PR TITLE
Query for last values outside time range

### LINKED ISSUE #139: failed to fetch query data: no aggregation values found for query
The error is displayed when you query for time range from grafana when no aggregation value is found for that time . The error is confusing for end users , many customers in Indiana Mfg Industries are getting confused what is happening.

image

### PR DESCRIPTION
**Pull request by toddtreece**
Fixes #139.

This requires the changes in https://github.com/grafana/grafana/pull/59444

example

The is the same query in Grafana 9.3.0 (without the changes in https://github.com/grafana/grafana/pull/59444)
image

### CODE REVIEW

**Review by ryantxu — APPROVED** [review]
🌮 looks great -- thanks

**Comment by kkmeghan** [comment]
@toddtreece Which version this be available and when ?

**Comment by taleena** [comment]
@toddtreece Correct me if I'm wrong, but @kkmeghan should be able to consume the changes which are now all merged (as mentioned [here](https://github.com/grafana/iot-sitewise-datasource/issues/139#issuecomment-1331232920)), and use the latest SiteWise release to test this out.

**Comment by toddtreece** [comment]
@taleena @kkmeghan this is available in `1.5.0` of the sitewise plugin. it will require using the `grafana/grafana:main` docker image, or building grafana locally since it's dependent on changes in grafana that have not been released yet.

**Pull request merged**
