### PR TITLE
fix: clear selected property when assets are removed

### PR DESCRIPTION
**Pull request by tracy-french**
**Which issue(s) this PR fixes**: https://github.com/grafana/iot-sitewise-datasource/issues/273

### CODE REVIEW

**Review by kevinwcyu — COMMENTED** [review]
Hi @tracy-french, thanks for the PR. It works when the old form styling is used, but not with the new form style (when the feature toggle `newFormStylingEnabled = true`).

I believe you'd just need to add `?? null` to the `value` prop to the "Property" select component in the `newFormStylingEnabled` branch of the render function on line 442.

```tsx
<Select
  id="property"
  aria-label="Property"
  isLoading={loading}
  options={properties}
  value={currentProperty ?? null} // <-----
  onChange={this.onPropertyChange}
  placeholder="Select a property"
  allowCustomValue={true}
  isSearchable={true}
  onCreateOption={this.onSetPropertyId}
  formatCreateLabel={(txt) => `Property ID: ${txt}`}
  menuPlacement="bottom"
/>
```

**Comment by tracy-french** [comment]
> Hi @tracy-french, thanks for the PR. It works when the old form styling is used, but not with the new form style (when the feature toggle `newFormStylingEnabled = true`).
> 
> I believe you'd just need to add `?? null` to the `value` prop to the "Property" select component in the `newFormStylingEnabled` branch of the render function on line 442.
> 
> ```tsx
> <Select
>   id="property"
>   aria-label="Property"
>   isLoading={loading}
>   options={properties}
>   value={currentProperty ?? null} // <-----
>   onChange={this.onPropertyChange}
>   placeholder="Select a property"
>   allowCustomValue={true}
>   isSearchable={true}
>   onCreateOption={this.onSetPropertyId}
>   formatCreateLabel={(txt) => `Property ID: ${txt}`}
>   menuPlacement="bottom"
> />
> ```

Thank you, @kevinwcyu! I'll make the change.

**Comment by tracy-french** [comment]
@kevinwcyu Updated!

**Review by kevinwcyu — APPROVED** [review]
Works great 🎉

**Pull request merged**
