### PR TITLE
feat: implement support for sitewise sql

### PR DESCRIPTION
**Pull request by mitchlee-amzn**
**What this PR does / why we need it**:
This PR extends the capabilities of the datasource plugin to support the SiteWise ExecuteQuery API, which allows customers to leverage adhoc SQL queries against their assets and properties.

**Which issue(s) this PR fixes**:
https://github.com/grafana/iot-sitewise-datasource/issues/267

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by mitchlee-amzn** [comment]
Note this isn't working yet, but I am getting quite a few changes here, so saving state while it compiles.

**Comment by fridgepoet** [comment]
Quick summary of what I've [mentioned on Slack](https://raintank-corp.slack.com/archives/C029UNXDFQV/p1703763761826659?thread_ts=1703100174.332739&cid=C029UNXDFQV): 
1. I would suggest that we bump the version of aws-sdk-go to v1.49.6 in a separate PR and you could put your ExecuteQuery changes on top of it. The reason is that there will be quite a few other changes along with that update, and it might be better if they didn’t take away from the focus of the ExecuteQuery PR. I’ve updated Sarah’s branch/PR with the changes needed for that update: https://github.com/grafana/iot-sitewise-datasource/pull/266 If you’re OK with that, we’ll complete the PR description and mark it as ready.

2. As mentioned above, I was able to [base your ExecuteQuery changes on top of the bump-aws-sdk branch](https://github.com/grafana/iot-sitewise-datasource/tree/ExecuteQuery-draft), and the frontend query seems to be reaching the backend.

**Comment by seb-koch** [comment]
This looks very promising. We'd be happy to test the implementation as we#re eager to use SQL within our ongoing customer projects with SiteWise. Thanks for your work, let us know if we can support in testing and even documenting the final use cases.

**Comment by vanPhilipp** [comment]
This feature provides a lot of extra flexibility, please continue.

**Comment by CFEazeti** [comment]
This would really help us to go forward in a customer project. Looking forward to this PR being finished. :+1:

**Comment by reinholdalex** [comment]
+1

**Comment by rastadrian** [comment]
+1

**Comment by tracy-french** [comment]
Happy to see all of the interest in this feature! We are actively working on prioritizing the completion of this feature and hope to continue the work soon.

**Pull request closed without merging**
